flagging_site/data/hobolink.py

HTTPException(status_code) has been replaced with abort(status_code)

Replaced HTTPException(status_code) with abort(status_code)

---

flagging_site/blueprints/api.py

this is a better way to do the api paremterization....but I'm not sure what the hour param does? any help?

parameterized api with flask.request two parameters hour and reach

---

flagging_site/app.py
tests/test_data.py

Test works. Commit based on feedback:
• Revised last_timestamp to conform to pandas conventions (last_timestamp = df['time'].iloc[-1])
• asserts based on pd.Timedelta of 30 minutes

Dev unit test data #37

---

flagging_site/templates/base.html

Added meta tag. Issue 68 
(add the url (og:image) for  for image to represent the website)
(add the url  (og:url) for of our website)

Dev_meta tag

---

.flaskenv
docs/README.md
flagging_site/app.py
flagging_site/blueprints/api.py
flagging_site/blueprints/boathouses_api.yml
flagging_site/blueprints/flagging.py
flagging_site/config.py
flagging_site/data/database.py
flagging_site/templates/api/index.html
flagging_site/templates/base.html

Combined all the changes to `dev_postgres` over the last week with a couple minor touch-ups to bring it all together and to fix some minor issues.

Updates to dev postgres

---

README.md
tests/test_data.py

Added some docstrings [https://github.com/codeforboston/flagging/issues/99#issue-711604257](url) and fixed a typo on README.

Minor typo fix and doc-string additions

---

docs/docs/admin.md
flagging_site/admin.py

Adding new route `/admin/update-db` that allows for manual updates. This PR is based on a request from Lisa at the CRWA.

Manual updater

---

flagging_site/app.py
flagging_site/blueprints/api.py
flagging_site/blueprints/flagging.py
flagging_site/blueprints/predictive_model_api.yml
flagging_site/config.py
flagging_site/templates/base.html
flagging_site/templates/flags.html
flagging_site/templates/index.html

Fulfilled the checklist from our off-season spike except for documentation.
I am not documenting it because we plan on adding this to the admin panel instead of relying on the env vars, so the way to turn the website on/off will be changing and thus should not be treated as if it's set in stone.

added boating season switch

---

flagging_site/admin.py
flagging_site/data/usgs.py
flagging_site/templates/admin/download.html
flagging_site/templates/admin/update.html
flagging_site/templates/base.html

Admin panel now has a download page instead of just a drop down, and there are now two ways to download: from the database or live. And the live version downloads 90 days of data.
This was based on some emails between Lisa and me regarding what they need to be able to do with the website.
This is already in production, so I'll just bring it in.

Updated admin panel

---

flagging_site/app.py
flagging_site/static/images/hamburger.svg
flagging_site/static/style.css
flagging_site/templates/base.html

Also moved the nav css to the section of the file where the rest of the header css is defined

Add hamburger menu and footer social links

---

flagging_site/static/dataframe.css
flagging_site/static/style.css
flagging_site/templates/about.html

more responsive elements

---

flagging_site/admin.py
flagging_site/blueprints/flagging.py
flagging_site/data/boathouses.py
flagging_site/data/queries/define_boathouse.sql
flagging_site/templates/_base.html
flagging_site/templates/_nav.html
flagging_site/templates/boathouses.html
requirements/_core.in
requirements/dev_osx.txt
requirements/dev_windows.txt
requirements/prod.txt

The boathouses are now visible on the map as pushpins

Displaying boathouses on a map

---

docs/src/setup.md
flagging_site/admin.py
flagging_site/app.py
flagging_site/config.py
flagging_site/data/database.py
flagging_site/data/predictive_models.py
flagging_site/data/usgs.py
flagging_site/templates/admin/index.html
pytest.ini
requirements/_dev_core.in
requirements/dev_osx.txt
requirements/dev_windows.in
requirements/dev_windows.txt
requirements/prod.in
requirements/prod.txt
tests/conftest.py
tests/test_api.py
tests/test_data.py
tests/test_site.py

make website go fast

---

flagging_site/twitter.py

The underlying problem is that the twitter bot was treating the safe/unsafe flag as if it were solely by reach. Now this flag has unique values for every boathouse.

Fixed twitter issue (issue 161)

---

flagging_site/admin.py
flagging_site/data/boathouses.py

Think this is the final major admin panel update, unless we figure out how to make the bools into flags easily.

Changes to admin panel

---

.github/workflows/tests.yml
docs/mkdocs.yml
docs/src/cloud/index.md
docs/src/cloud/manual_heroku_deployment.md
docs/src/development/data.md
docs/src/development/frontend.md
docs/src/development/index.md
docs/src/development/predictive_models.md
docs/src/index.md
docs/src/setup.md
flagging_site/admin.py
flagging_site/blueprints/flagging.py
flagging_site/data/boathouses.py
flagging_site/data/predictive_models.py
flagging_site/templates/README.md
flagging_site/templates/admin/list_boathouses.html
flagging_site/twitter.py
tests/test_data.py
tests/test_site.py

PR merges changes made in dev to main, cleaning up the boathouse admin panel.
---
With this PR in, the flagging site is nearly "done" for the 2021 boating season.
I think the last thing we need are unit-tests for the twitter bot. That thing has been decommissioned for a while, might need to make sure it's really truly working after all the changes we've made since end of boating season.
Otherwise, the outstanding issues are basically just docs, docstrings, refactors, and tests. We already have tons of docs and docstrings. If you want to do these things, please be my guest, but they will not be prioritized for the time being.
- ✅ Refactoring. I'd say I'm about 2/3 of the way through the refactors I wanted to make to the website.
- ✅ More docs, more docstrings.
- ✅ More tests. We already …

Final(-ish) PR for 2021 boating season.

---

.github/workflows/tests.yml
pytest.ini
tests/test_cli.py

Sure, why not. We almost had a grammatical issue with the tweet caused by a lack of a space. Might as well test for it.

Grammar checks

---

flagging_site/app.py
flagging_site/blueprints/flagging.py
flagging_site/mail.py
flagging_site/static/style.css
flagging_site/templates/api/_boathouses.R.jinja
flagging_site/templates/api/_boathouses.py.jinja
flagging_site/templates/api/_model_outputs.R.jinja
flagging_site/templates/api/_model_outputs.py.jinja
flagging_site/templates/api/index.html
flagging_site/templates/index.html
flagging_site/templates/mail/error.html
flagging_site/templates/mail/update_db_fail.html
flagging_site/twitter.py
tests/conftest.py
tests/test_site.py

Added a nice little refactor that opens up a neat test case-- the example code inside of `/api` is now covered by tests!

refactor api home page + new test case

---

app/admin/views/data.py
app/config.py
app/data/celery.py
app/data/processing/predictive_models/v1.py
app/data/processing/predictive_models/v2.py
app/data/processing/predictive_models/v3.py
app/main.py
pytest.ini
requirements.in
requirements.txt
tests/test_cli.py

Also consolidate Twitter stuff, which is sadly on its way out. (Doesn't even work right now.)

add sentry

---

alembic/versions/rev005.py
app/admin/views/data.py
app/data/celery.py
app/data/models/prediction.py
app/data/processing/core.py
app/data/processing/predictive_models/v1.py
app/data/processing/predictive_models/v2.py
app/data/processing/predictive_models/v3.py
app/data/processing/predictive_models/v4.py
app/data/processing/predictive_models/v4_copy.py
app/data/processing/usgs.py
app/data/processing/usgs_copy.py
app/main.py
app/templates/about.html
app/templates/admin/download.html
app/templates/mail/periodic_data_delivery.html
app/templates/model_outputs.html
docker-compose.yml
docs/src/development_resources/shell.md
tests/test_data.py
tests/test_site.py

Changed files:
- docker-compose.yml
removed the versions module
- .env 
commented and added some lines to be able to access everything locally
hobolink account details 
- app/data/processing/usgs.py 
edits to request_to_usgs to be able to request more data
edits to parse_usgs_data to be able to parse more data
edits to get_live_usgs_data to return dict of two datasets
edit find all references of get_live_usgs_data and change it to include have site_no, duplicating for both sites
edit the USGS_ROWS_PER_HOUR variable and all references -> now two global imported variables 
- core.py
add model v4 
edits to reference of get_live_usgs_data
NEED TO CHANGE THE MODEL NUMBER TO V4
- celery.py
references get_live_usgs_data - no need to change. **kwargs go to every variable implementation
- v4.py …

Update model version 4 - January 2025
